CREATE TABLE IF NOT EXISTS t_company (
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) DEFAULT NULL,
	ceo VARCHAR(100) DEFAULT NULL,
	adress TEXT DEFAULT NULL,
	birthDate DATE DEFAULT NULL,
	description TEXT DEFAULT NULL,
	telefon1 VARCHAR(50) DEFAULT NULL,
	telefon2 VARCHAR(50) DEFAULT NULL,
	email VARCHAR(100) DEFAULT NULL,
	logo TEXT DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;