CREATE TABLE IF NOT EXISTS t_project (
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) DEFAULT NULL,
	titre TEXT DEFAULT NULL,
	adress TEXT DEFAULT NULL,
	size DECIMAL(12,2) DEFAULT NULL,
	birthDate DATE DEFAULT NULL,
	description TEXT DEFAULT NULL,
	status VARCHAR(50) DEFAULT NULL,
	construction INT(12) DEFAULT NULL,
	finition INT(12) DEFAULT NULL,
	idCompany INT(12) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;